// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domain.Migrations
{
    [DbContext(typeof(FuncionarioContext))]
    [Migration("20220427181208_v7")]
    partial class v7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Beneficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NivelID")
                        .HasColumnType("int");

                    b.Property<int?>("TipoBeneficioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NivelID");

                    b.HasIndex("TipoBeneficioId");

                    b.ToTable("Beneficios");
                });

            modelBuilder.Entity("Domain.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("Domain.Deposito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("Datetime");

                    b.Property<double>("ValorDepositoFuncionario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Depositos");
                });

            modelBuilder.Entity("Domain.DepositoBeneficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BeneficioId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BeneficioId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("DepositosBeneficios");
                });

            modelBuilder.Entity("Domain.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("modalidadeCargoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("modalidadeCargoId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Domain.ModalidadeCargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CargoID")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadeContratoID")
                        .HasColumnType("int");

                    b.Property<int?>("NivelID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoID");

                    b.HasIndex("NivelID");

                    b.ToTable("ModalidadeCargos");
                });

            modelBuilder.Entity("Domain.ModalidadeDeContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ModalidadeDeContratos");
                });

            modelBuilder.Entity("Domain.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NiveisFuncionario");
                });

            modelBuilder.Entity("Domain.TipoBeneficio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Beneficio")
                        .HasColumnType("int");

                    b.Property<int?>("BeneficioId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Percent")
                        .HasColumnType("real");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Beneficio");

                    b.ToTable("TipoBeneficios");
                });

            modelBuilder.Entity("Domain.Beneficio", b =>
                {
                    b.HasOne("Domain.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelID");

                    b.HasOne("Domain.TipoBeneficio", "TipoBeneficio")
                        .WithMany()
                        .HasForeignKey("TipoBeneficioId");

                    b.Navigation("Nivel");

                    b.Navigation("TipoBeneficio");
                });

            modelBuilder.Entity("Domain.DepositoBeneficio", b =>
                {
                    b.HasOne("Domain.Beneficio", "Beneficio")
                        .WithMany("DepositoBeneficios")
                        .HasForeignKey("BeneficioId");

                    b.HasOne("Domain.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.Navigation("Beneficio");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Domain.Funcionario", b =>
                {
                    b.HasOne("Domain.ModalidadeCargo", "ModalidadeCargo")
                        .WithMany()
                        .HasForeignKey("modalidadeCargoId");

                    b.Navigation("ModalidadeCargo");
                });

            modelBuilder.Entity("Domain.ModalidadeCargo", b =>
                {
                    b.HasOne("Domain.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoID");

                    b.HasOne("Domain.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelID");

                    b.Navigation("Cargo");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("Domain.TipoBeneficio", b =>
                {
                    b.HasOne("Domain.Beneficio", "Beneficios")
                        .WithMany()
                        .HasForeignKey("Beneficio");

                    b.Navigation("Beneficios");
                });

            modelBuilder.Entity("Domain.Beneficio", b =>
                {
                    b.Navigation("DepositoBeneficios");
                });
#pragma warning restore 612, 618
        }
    }
}
